export const ADD_TO_WATCHLATER = "ADD_TO_WATCHLATER";
export const REMOVE_FROM_WATCHLATER = "REMOVE_FROM_WATCHLATER";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
export const ADD_VIDEO_TO_PLAYLIST = "ADD_VIDEO_TO_PLAYLIST";
export const REMOVE_VIDEO_FROM_PLAYLIST = "REMOVE_VIDEO_FROM_PLAYLIST";
export const ADD_TO_NOTES = "ADD_TO_NOTES";
export const REMOVE_FROM_NOTES = "REMOVE_FROM_NOTES";
